// <auto-generated />
namespace KaleMeCrazy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class intiMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intiMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202103090512274_intiMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
